development:
      host: localhost
      adapter: mysql
      database: nicolas
      port: 3306
      username: root
      password: 123

test: &test
      host: localhost
      adapter: mysql
      database: fedena_two_new
      port: 3306
      username: root
      password: foradian

production:
      host: localhost
      adapter: mysql
      database: nicolas
      port: 3306
      username: root
      password: 123
cucumber:
  <<: *test
